name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: |
        XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text=coverage.txt --whitelist src/ tests/
        cat coverage.txt
        COVERAGE=$(cat coverage.txt | grep -E '^\s+Lines:.*' | perl -pe 's/(.*?)(\d+\.\d+%).*/$2/')
        echo $COVERAGE
        echo "COVERAGE=$(echo ${COVERAGE})" >> $GITHUB_ENV

    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 0f0d97def8e970cfb455e528c703c506
        filename: fas-routing__main.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: blueviolet
        namedLogo: php